#!/usr/bin/env bash
# build-agents.sh — assemble AGENTS.md (home) and AGENTS.work.md (work) from
# fragments in agents-md/. Outputs are committed; edit fragments, never outputs.
#
# Usage:
#   ./build-agents.sh          regenerate both files
#   ./build-agents.sh --check  exit 1 if committed outputs drift from fragments
set -euo pipefail
cd "$(dirname "$0")"

HEADER='<!-- GENERATED from agents-md/ — edit fragments, run build-agents.sh. Do not edit this file. -->'

build() {
  local out="$1"; shift
  {
    printf '%s\n\n' "$HEADER"
    for f in "$@"; do
      cat "agents-md/$f"
      printf '\n'
    done
  } > "$out"
}

emit() {
  # persona-core/standards/ops/ladder are shared across harnesses;
  # persona-pi holds the pi-only sections (Tools, Delegation, memory, PDF),
  # claude-delta the Claude-Code-only ones (subagents, hooks, MCP memory).
  # ladder.md is concatenated LAST in every variant (recency slot).
  build "$1/AGENTS.md"      persona-core.md persona-pi.md standards.md ops.md ladder.md
  build "$1/AGENTS.work.md" persona-core.md persona-pi.md standards.md ops.md env.work.md ladder.md
  build "$1/CLAUDE.md"      persona-core.md claude-delta.md standards.md ops.md ladder.md
}

if [[ "${1:-}" == "--check" ]]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  emit "$tmp"
  if diff -q "$tmp/AGENTS.md" AGENTS.md >/dev/null \
    && diff -q "$tmp/AGENTS.work.md" AGENTS.work.md >/dev/null \
    && diff -q "$tmp/CLAUDE.md" CLAUDE.md >/dev/null; then
    echo "OK: AGENTS/CLAUDE files match fragments"
  else
    echo "DRIFT: generated files do not match fragments — run build-agents.sh" >&2
    exit 1
  fi
else
  emit .
  echo "Wrote AGENTS.md ($(wc -l <AGENTS.md | tr -d ' ') lines), AGENTS.work.md ($(wc -l <AGENTS.work.md | tr -d ' ') lines), CLAUDE.md ($(wc -l <CLAUDE.md | tr -d ' ') lines)"
fi
